### ISSUE TITLE
Feature: filter by collection

### ISSUE THREAD

**Issue by onecrayon** [onecrayon/api.ashes.live#53]
Filtration by collection is already supported by the filter logic, but I need to implement the ability to actually save information about what is in a user's collection. Should probably be its own endpoint, but maybe instead treat it as a generic option on the existing user endpoints? I'm on the fence; benefit of a standard option is then I have an easy way to cache that info (when we inevitably fetch the user), but maybe it makes sense to fetch it when they open the interface element to adjust it since we have to load the releases at that point, anyway.

I also need to decide it I want to completely filter cards out that they don't own, or if I should gray them out in the card browser and only filter completely in deckbuilding mode.

## Tasks

* [x] GET `/v2/releases?show_legacy=false` to list all public releases on the site. If the user is authenticated, it will include a flag to indicate which releases are in their collection.
* [x] PUT `/v2/releases/mine` to mark which releases are part of the user's collection
* [x] PATCH `/v2/releases/{release_stub}` (ADMIN ONLY) to make a particular release public
* [x] GET `/v2/cards` modifications
    * [x] Allow filtering by arbitrary releases in addition to "mine"
    * [x] Allow ordering by release (then by type, then alphabetically)
    * [x] Ordering by type should use the front-end's deck display ordering (Phoenixborn, Ready Spell, Ally, Action Spell, Reaction Spell, Conjuration, Conjured Alteration Spell)

Filtering decks by releases is unfortunately not feasible, as best I can tell (because there's no good way to exclude a deck based on all of its DeckCard relationships *and* DeckDie relationships being within a given set of releases)

**Comment by onecrayon** [comment]
I've got a request from Dijon to allow filtering by arbitrary releases when viewing the card listing (e.g. through URL query strings) since that would allow him to link to a specific set of cards that can be used in an Ashteki tournament.

I need to give this one some thought. I can see how this would be useful, but at the same time it's kind of a trick to manage that *and* collections, which I think are the more typical usecase for this sort of filtration. I suppose the collection could be the default filter, and then users could change it? But what about when you link to a page with the filters--would it change the collection? Reset your browser-side defaults? Or maybe we filter by collection as a button in the interface, and then have the full list down below (which just modifies this session)?
